// Note model for key study notes generated by AI

class Note {
  final String id;
  final String projectId;
  final String? fileId; // 關聯的文件ID
  final String title; // 標題
  final List<String> mainConcepts; // 主要概念
  final String detailedExplanation; // 詳細說明
  final String importance; // 重要性標記: 'high' | 'medium' | 'low'
  final List<String> keywords; // 關鍵字
  final DateTime createdAt;
  final bool isFavorite; // 是否收藏

  const Note({
    required this.id,
    required this.projectId,
    this.fileId,
    required this.title,
    required this.mainConcepts,
    required this.detailedExplanation,
    this.importance = 'medium',
    required this.keywords,
    required this.createdAt,
    this.isFavorite = false,
  });

  Note copyWith({
    String? id,
    String? projectId,
    String? fileId,
    String? title,
    List<String>? mainConcepts,
    String? detailedExplanation,
    String? importance,
    List<String>? keywords,
    DateTime? createdAt,
    bool? isFavorite,
  }) {
    return Note(
      id: id ?? this.id,
      projectId: projectId ?? this.projectId,
      fileId: fileId ?? this.fileId,
      title: title ?? this.title,
      mainConcepts: mainConcepts ?? this.mainConcepts,
      detailedExplanation: detailedExplanation ?? this.detailedExplanation,
      importance: importance ?? this.importance,
      keywords: keywords ?? this.keywords,
      createdAt: createdAt ?? this.createdAt,
      isFavorite: isFavorite ?? this.isFavorite,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'projectId': projectId,
      'fileId': fileId,
      'title': title,
      'mainConcepts': mainConcepts,
      'detailedExplanation': detailedExplanation,
      'importance': importance,
      'keywords': keywords,
      'createdAt': createdAt.toIso8601String(),
      'isFavorite': isFavorite,
    };
  }

  factory Note.fromJson(Map<String, dynamic> json) {
    return Note(
      id: json['id'] as String,
      projectId: json['projectId'] as String,
      fileId: json['fileId'] as String?,
      title: json['title'] as String,
      mainConcepts: (json['mainConcepts'] as List).map((e) => e as String).toList(),
      detailedExplanation: json['detailedExplanation'] as String,
      importance: json['importance'] as String? ?? 'medium',
      keywords: (json['keywords'] as List).map((e) => e as String).toList(),
      createdAt: DateTime.parse(json['createdAt'] as String),
      isFavorite: json['isFavorite'] as bool? ?? false,
    );
  }

  /// 重要性對應的顯示文字
  String get importanceLabel {
    switch (importance) {
      case 'high':
        return '高';
      case 'medium':
        return '中';
      case 'low':
        return '低';
      default:
        return '中';
    }
  }
}
