// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfLH-M9oMqPAcV678q4mNdlrN1aNebkcE',
    appId: '1:1007172394951:web:0f94329b58f829e10283e2',
    messagingSenderId: '1007172394951',
    projectId: 'ghote-app',
    authDomain: 'ghote-app.firebaseapp.com',
    storageBucket: 'ghote-app.firebasestorage.app',
    measurementId: 'G-3KSWRLXDKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxuGlf6K4gOlemAZBO7TlFPwBvKNnkolA',
    appId: '1:1007172394951:android:8f8ebc2292e37bc50283e2',
    messagingSenderId: '1007172394951',
    projectId: 'ghote-app',
    storageBucket: 'ghote-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAITT7-XYdpe0nfdxR8GYMFICPcVKBJjw',
    appId: '1:1007172394951:ios:8d540b9b847f6c7e0283e2',
    messagingSenderId: '1007172394951',
    projectId: 'ghote-app',
    storageBucket: 'ghote-app.firebasestorage.app',
    iosBundleId: 'com.example.ghote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAITT7-XYdpe0nfdxR8GYMFICPcVKBJjw',
    appId: '1:1007172394951:ios:8d540b9b847f6c7e0283e2',
    messagingSenderId: '1007172394951',
    projectId: 'ghote-app',
    storageBucket: 'ghote-app.firebasestorage.app',
    iosBundleId: 'com.example.ghote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfLH-M9oMqPAcV678q4mNdlrN1aNebkcE',
    appId: '1:1007172394951:web:010b8a2ea09340560283e2',
    messagingSenderId: '1007172394951',
    projectId: 'ghote-app',
    authDomain: 'ghote-app.firebaseapp.com',
    storageBucket: 'ghote-app.firebasestorage.app',
    measurementId: 'G-4RCHPGB8EG',
  );
}
